version: '3.7'

services:
  python-vosk:
    container_name: python-vosk
    build:
      context: .
      dockerfile: docker/python38/Dockerfile
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - ./app:/application
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/snd:/dev/snd
    entrypoint: python main.py